import Head from "next/head";
import React from "react";
import Header from "./Header";

const Layout = ({ title, children }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="wrapper">
       <Header/>
        <main>{children}</main>
        <footer><h1>this is footer</h1></footer>
      </div>
    </>
  );
};

export default Layout;
